package com.smartbox.jobster.entity.ref;

import io.jmix.core.metamodel.datatype.EnumClass;
import org.springframework.lang.Nullable;


public enum SettingType implements EnumClass<String> {

    QUESTIONNAIRE_OPENED("QUESTIONNAIRE_OPENED"),
    QUESTIONNAIRE_COMPLETED("QUESTIONNAIRE_COMPLETED"),
    ABOUT_JOBSTER("ABOUT_JOBSTER"),
    CONTACT_SYS_ADMIN("CONTACT_SYS_ADMIN"),
    SELECT_LANGUAGE("SELECT_LANGUAGE"),
    FEEDBACK("FEEDBACK"),
    SKIP("SKIP"),
    BACK("BACK"),
    NEXT("NEXT"),
    MAIN_MENU("MAIN_MENU"),
    DISTANCE("DISTANCE"),
    BRANCH_LOCATION("BRANCH_LOCATION"),
    QUESTIONNAIRE_LIMIT_MESSAGE("QUESTIONNAIRE_LIMIT_MESSAGE"),
    QUESTIONNAIRE_FINISH_MESSAGE("QUESTIONNAIRE_FINISH_MESSAGE"),
    EMPTY_QUESTIONNAIRE("EMPTY_QUESTIONNAIRE"),
    QUESTION_NOT_FOUND("QUESTION_NOT_FOUND"),
    INVALID_QUESTION_ANSWER("INVALID_QUESTION_ANSWER"),
    WRONG_CHOICE("WRONG_CHOICE"),
    QUIZ_QUESTIONS_AMOUNT("QUIZ_QUESTIONS_AMOUNT"),
    QUIZ_START_BTN("QUIZ_START_BTN"),
    QUIZ_REQUIRED_TEXT("QUIZ_REQUIRED_TEXT"),
    QUIZ_RESULT("QUIZ_RESULT"),
    QUIZ_TIME_LIMIT("QUIZ_TIME_LIMIT"),
    SHARE_PHONE("SHARE_PHONE"),
    SHARE_EMAIL("SHARE_EMAIL"),
    SHARE_STAFF_NUMBER("SHARE_STAFF_NUMBER"),
    SHARE_LOCATION_TEXT("SHARE_LOCATION_TEXT"),
    SHARE_LOCATION_REQUEST("SHARE_LOCATION_REQUEST"),
    CONFIRMATION_REQUEST("CONFIRMATION_REQUEST"),
    INVALID_PHONE("INVALID_PHONE"),
    INVALID_EMAIL("INVALID_EMAIL"),
    INVALID_CODE("INVALID_CODE"),
    SELECT_LOGIN_TYPE("SELECT_LOGIN_TYPE"),
    VERIFY_CODE("VERIFY_CODE"),
    VACANCY_INFO("VACANCY_INFO"),
    WEB_APP_VACANCY("WEB_APP_VACANCY"),
    EMPLOYEE_NOT_FOUND("EMPLOYEE_NOT_FOUND"),
    WELCOME_EMPLOYEE("WELCOME_EMPLOYEE"),
    SURVEY_NEXT_QUESTION("SURVEY_NEXT_QUESTION"),
    SURVEY_FINISH_MESSAGE("SURVEY_FINISH_MESSAGE"),
    SURVEY_START_MESSAGE("SURVEY_START_MESSAGE"),
    SURVEY_FINISH_BUTTON("SURVEY_FINISH_BUTTON"),
    TASK_ASSIGNED("TASK_ASSIGNED"),
    TASK_FINISH_UNABLE("TASK_FINISH_UNABLE"),
    TASK_FINISH_BUTTON("TASK_FINISH_BUTTON"),
    TASK_FINISH_MESSAGE("TASK_FINISH_MESSAGE"),
    SHARE_PINFL("SHARE_PINFL"),
    SHARE_PERSONNEL_NUMBER("SHARE_PERSONNEL_NUMBER"),
    SHARE_BIRTH_DATE("SHARE_BIRTH_DATE"),
    SELECT_MONTH("SELECT_MONTH"),
    INFORMATION_NOT_FOUND("INFORMATION_NOT_FOUND"),
    WRONG_PHONE_AND_CONTACT_SYS_ADMIN("WRONG_PHONE_AND_CONTACT_SYS_ADMIN"),
    POWERED_BY("POWERED_BY"),
    BANNED("BANNED"),
    CHECK_IN("CHECK_IN"),
    CHECK_OUT("CHECK_OUT"),
    CHECK_OUT_BTN("CHECK_OUT_BTN"),
    MY_ATTENDANCE("MY_ATTENDANCE"),
    REGULAR("REGULAR"),
    OVERTIME("OVERTIME"),
    LOGIN_REQUIRED("LOGIN_REQUIRED"),
    LOGGED_IN("LOGGED_IN"),
    SUCCESS_IN("SUCCESS_IN"),
    SUCCESS_IN_OVERTIME("SUCCESS_IN_OVERTIME"),
    SUCCESS_OUT("SUCCESS_OUT"),
    SUCCESS_OUT_OVERTIME("SUCCESS_OUT"),
    OVERTIME_REASON("OVERTIME_REASON"),
    FORGOT_CHECK_IN("FORGOT_CHECK_IN"),
    FORGOT_CHECK_OUT("FORGOT_CHECK_OUT"),
    CHECK_UP_CONFIRM("CHECK_UP_CONFIRM"),
    PREVIOUS_QUESTION_NOT_FOUND("PREVIOUS_QUESTION_NOT_FOUND"),
    START_QUESTIONNAIRE("START_QUESTIONNAIRE"),
    SELECT_BRANCH("SELECT_BRANCH"),
    EVENT_RESPONSE_ACCEPT("EVENT_RESPONSE_ACCEPT"),
    EVENT_RESPONSE_DECLINE("EVENT_RESPONSE_DECLINE"),
    MANAGER_EVENT_RESPONSE_ACCEPT("MANAGER_EVENT_RESPONSE_ACCEPT"),
    MANAGER_EVENT_RESPONSE_DECLINE("MANAGER_EVENT_RESPONSE_DECLINE"),
    PHOTO_VALIDATION("PHOTO_VALIDATION"),
    PHOTO_UPDATED_SUCCESSFULLY("PHOTO_UPDATED_SUCCESSFULLY"),
    SCHEDULE_SELECT_WEEKDAY("SCHEDULE_SELECT_WEEKDAY"),
    SCHEDULE_SELECT_DATETIME("SCHEDULE_SELECT_DATETIME"),
    SCHEDULE_SELECTED_EVENT("SCHEDULE_SELECTED_EVENT"),
    SCHEDULE_EMPTY_SLOTS("SCHEDULE_EMPTY_SLOTS"),
    SCHEDULE_UNAVAILABLE_SLOT("SCHEDULE_UNAVAILABLE_SLOT"),
    SHARE_BUTTON_TEXT("SHARE_BUTTON_TEXT"),
    EVENT_CANCEL_MESSAGE("EVENT_CANCEL_MESSAGE"),
    EVENT_ACCEPTED_MESSAGE("EVENT_ACCEPTED_MESSAGE"),
    EVENT_CANCEL_REASON_MESSAGE("EVENT_CANCEL_REASON_MESSAGE"),
    VIEW_CANDIDATE("VIEW_CANDIDATE"),
    WELCOME_MANAGER("WELCOME_MANAGER"),
    MANAGER("MANAGER"),
    MANAGER_COMMENT("MANAGER_COMMENT"),
    RECRUITER("RECRUITER"),
    RECRUITER_COMMENT("RECRUITER_COMMENT"),
    MANAGER_SUCCESSFULLY("MANAGER_SUCCESSFULLY"),
    MANAGER_CANDIDATES_NOT_FOUND("MANAGER_CANDIDATES_NOT_FOUND"),
    MANAGER_PENDING("MANAGER_PENDING"),
    MANAGER_PENDING_CANDIDATES("MANAGER_PENDING_CANDIDATES"),
    MANAGER_RESERVED("MANAGER_RESERVED"),
    MANAGER_RESERVED_CANDIDATES("MANAGER_RESERVED_CANDIDATES"),
    MANAGER_REVIEWED("MANAGER_REVIEWED"),
    MANAGER_REVIEWED_CANDIDATES("MANAGER_REVIEWED_CANDIDATES"),
    MANAGER_HISTORY("MANAGER_HISTORY"),
    MANAGER_HISTORY_CANDIDATES("MANAGER_HISTORY_CANDIDATES"),
    MANAGER_REVIEW_PERSON("MANAGER_REVIEW_PERSON"),
    MANAGER_ACCEPT_PERSON("MANAGER_ACCEPT_PERSON"),
    MANAGER_REJECT_PERSON("MANAGER_REJECT_PERSON"),
    MANAGER_RESERVE_PERSON("MANAGER_RESERVE_PERSON"),
    MANAGER_HISTORY_PERSON("MANAGER_HISTORY_PERSON"),
    MANAGER_INFO_PERSON("MANAGER_INFO_PERSON"),
    MANAGER_LEAVE_COMMENT("MANAGER_LEAVE_COMMENT"),
    REQUEST_POSITION("REQUEST_POSITION"),
    REQUEST_DEPARTMENT("REQUEST_DEPARTMENT"),
    REQUEST_AMOUNT_OF_JOB("REQUEST_AMOUNT_OF_JOB"),
    REQUEST_AVAILABLE("REQUEST_AVAILABLE"),
    REQUEST_PUBLISH_DATE("REQUEST_PUBLISH_DATE"),
    REQUEST_EMPTY("REQUEST_EMPTY"),
    ;

    public final String id;

    SettingType(String id) {
        // Реализация не публикуется: коммерческая тайна.
        throw new UnsupportedOperationException("Implementation not published");
    }


    public String getId() {
        // Реализация не публикуется: коммерческая тайна.
        throw new UnsupportedOperationException("Implementation not published");
    }

    @Nullable
    public static SettingType fromId(String id) {
        // Реализация не публикуется: коммерческая тайна.
        throw new UnsupportedOperationException("Implementation not published");
    }
}