package com.smartbox.jobster.security;

import io.jmix.security.role.annotation.ResourceRole;
import io.jmix.security.role.annotation.SpecificPolicy;
import io.jmix.securityflowui.role.annotation.ViewPolicy;

@ResourceRole(name = "Standard views", code = StandardViewRole.CODE, scope = "UI")
public interface StandardViewRole extends WriteEntityRole, MinimalViewRole {
    String CODE = "standard-view-role";

    @SpecificPolicy(resources = {"ui.genericfilter.modifyConfiguration", "ui.genericfilter.modifyJpqlCondition", "ui.showExceptionDetails", "ui.genericfilter.modifyGlobalConfiguration"})
    void standardSpecific();

    @ViewPolicy(viewIds = {"jb_AbsentReason.detail", "jb_ActionDetailView", "jb_ActionView", "jb_AnswerFormat.detail", "jb_AutoFillTemplate.detail", "jb_AutoFillTemplate.master", "jb_TgBot.detail", "jb_BranchType.detail", "jb_CancelReason.detail", "jb_BigImageView", "chatView", "jb_ShareFileView", "jb_Country.detail", "jb_Department.detail", "jb_DepartmentCategory.detail", "jb_Education.detail", "jb_Experience.detail", "jb_KanbanStageAction.list", "jb_KanbanStage.detail", "jb_KanbanTemplate.detail", "jb_KanbanTemplate.list", "jb_Label.detail", "jb_Language.detail", "jb_EntityMapping.detail", "jb_EntityMapping.list", "jb_EntityMappingView", "jb_EntityMappingProperty.list", "jb_MappingPropertyCondition.detail", "jb_PropertyConditionDefault.detail", "jb_MaritalStatus.detail", "jb_Menu.list", "jb_Post.detail", "jb_MenuRole.detail", "jb_NavigationRole.detail", "jb_OrgChartView", "jb_Position.detail", "jb_Position.master", "jb_Questionnaire", "jb_Questionnaire.detail", "jb_Question.detail", "jb_QuestionForm", "jb_QuestionCondition.detail", "jb_QuestionOption.detail", "jb_QuizAnswer.detail", "jb_QuizAnswer.list", "jb_Quiz.detail", "jb_Quiz.list", "jb_QuizQuestion.detail", "jb_QuizQuestion.list", "jb_RedisManagerView", "jb_Reference.detail", "jb_Region.detail", "jb_Setting.detail", "jb_RefSource.detail", "jb_Request.detail", "jb_Request.list", "jb_RequestQuestionnaireView", "jb_Request-mobile.list", "jb_Robot.detail", "jb_Robot.list", "jb_RobotMobile.list", "RobotMobileCardFragment", "jb_RobotActionsView", "jb_RobotCondition.detail", "jb_RobotConditionManagerInterview.detail", "jb_RobotConditionManagerResponse.detail", "jb_RoleType.detail", "jb_RoleType.list", "jb_SalaryLevel.detail", "jb_Sequence.detail", "jb_SpeechAssessmentView", "jb_SpeechAssessmentInfoView", "jb_Survey.detail", "jb_Survey.list", "jb_SendSurveyView", "jb_SurveyAnswer.detail", "SurveyAnswerCardFragment", "SurveyCardFragment", "jb_SurveyQuestion.detail", "jb_SurveyQuestion.list", "SurveyQuestionCardFragment", "jb_SurveyQuestionCondition.detail", "SurveyConditionCardFragment", "jb_SurveyQuestionGroup.detail", "jb_HhSyncView", "jb_Vacancy.detail", "jb_Vacancy.list", "jb_WorkPosition.detail", "jb_WorkSchedule.detail", "jb_SalaryData.detail", "jb_SalaryData.list", "jb_SalaryInfo.detail", "jb_SalaryInfo.list", "jb_FieldsImportView", "jb_TemplateField.detail", "jb_TemplateField.list", "jb_Template.detail", "jb_Template.list", "headerPropertyFilterLayout", "flowui_AddConditionView", "flowui_GroupFilterCondition.detail", "flowui_JpqlFilterCondition.detail", "flowui_PropertyFilterCondition.detail", "inputDialog", "multiValueSelectDialog", "flowui_DateIntervalDialog", "jb_ExcelView", "jb_PositionType.detail", "jb_RequestCancelReason.list", "jb_RequestCancelReason.detail", "jb_TranslationView", "jb_RequestType.list", "jb_RequestType.detail"})
    void standardViews();
}